import type {
  HeroSettingsData,
  HomepageSectionData,
  SitePageData,
} from "@/lib/cms/types";

export const defaultHero: HeroSettingsData = {
  eyebrow: "Spring Collection is here!",
  headline: "Dress little adventurers in",
  headlineAccent: "joyful",
  description:
    "Soft fabrics, playful prints, and comfy fits for every age. From cozy onesies to adventure-ready outfits.",
  backgroundType: "gradient",
  backgroundImageUrl: null,
  gradientPreset: "blush-sky-mint",
  buttons: [
    { id: "1", label: "Shop Now", href: "/shop", variant: "default" },
    { id: "2", label: "New Arrivals", href: "/shop?new=true", variant: "outline" },
    { id: "3", label: "Shop Sale", href: "/shop?sale=true", variant: "outline" },
  ],
  productTiles: [],
};

export const defaultHomepageSections: HomepageSectionData[] = [
  {
    key: "CATEGORIES",
    enabled: true,
    eyebrow: "The Collection",
    title: "Shop by category",
    description: "Browse by age and gender to find the perfect fit",
    viewAllLabel: "View all",
    viewAllHref: "/shop",
    productLimit: 4,
    sortBy: "NEWEST",
    includeSiteWideSale: true,
  },
  {
    key: "NEW_ARRIVALS",
    enabled: true,
    eyebrow: null,
    title: "New Arrivals",
    description: "Fresh picks just landed",
    viewAllLabel: "View all",
    viewAllHref: "/shop?new=true",
    productLimit: 4,
    sortBy: "NEWEST",
    includeSiteWideSale: true,
  },
  {
    key: "ON_SALE",
    enabled: true,
    eyebrow: null,
    title: "On Sale",
    description: "Limited-time deals",
    viewAllLabel: "View all",
    viewAllHref: "/shop?sale=true",
    productLimit: 6,
    sortBy: "UPDATED",
    includeSiteWideSale: true,
  },
  {
    key: "CLEARANCE",
    enabled: true,
    eyebrow: null,
    title: "Clearance",
    description: "Last-chance styles at deep discounts",
    viewAllLabel: "View all",
    viewAllHref: "/shop?clearance=true",
    productLimit: 4,
    sortBy: "UPDATED",
    includeSiteWideSale: true,
  },
  {
    key: "TRENDING",
    enabled: true,
    eyebrow: null,
    title: "Trending Now",
    description: "Parent favorites this week",
    viewAllLabel: "View all",
    viewAllHref: "/shop?sort=trending",
    productLimit: 4,
    sortBy: "TRENDING_SCORE",
    includeSiteWideSale: true,
  },
];

export const defaultSitePages: SitePageData[] = [
  {
    slug: "privacy",
    title: "Privacy Policy",
    subtitle: null,
    body: "",
    published: false,
    showInNav: true,
    contactEmail: null,
    contactPhone: null,
    contactAddress: null,
    contactHours: null,
  },
  {
    slug: "terms",
    title: "Terms of Use",
    subtitle: null,
    body: "",
    published: false,
    showInNav: true,
    contactEmail: null,
    contactPhone: null,
    contactAddress: null,
    contactHours: null,
  },
  {
    slug: "returns",
    title: "Returns & Exchanges",
    subtitle: null,
    body: "",
    published: false,
    showInNav: true,
    contactEmail: null,
    contactPhone: null,
    contactAddress: null,
    contactHours: null,
  },
  {
    slug: "contact",
    title: "Get in Touch",
    subtitle:
      "Questions about sizing, orders, or our products? We're here to help!",
    body: "",
    published: true,
    showInNav: true,
    contactEmail: "hello@theminiwear.com",
    contactPhone: "(555) 123-4567",
    contactAddress: "123 Kids Lane, Portland, OR 97201",
    contactHours: "Mon–Fri: 9am – 5pm PST\nSat–Sun: Closed",
  },
];
